#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

char inp_line[2048];

char fid_str[2048];
char fid_fname[2048];
int  eid_int;
int  fid_int;

#define MAX_FID_NUM 50
#define MAX_FID_LEN 128

char fid_tbl[MAX_FID_NUM][MAX_FID_LEN];

FILE *fid_file;

int main(int argc, char* argv[])
{
    int rc;
    char *s_pos;
    memset(fid_tbl, 0, sizeof(fid_tbl));

    if (argc < 2)
    {
        printf("Please specify header file with local FIDs.\n");
        exit(EXIT_FAILURE);
    }

    fid_file = fopen(argv[1], "r");
    if (NULL == fid_file)
    {
        printf("Can't open header file with local FIDs: %s.\n", argv[1]);
        exit(EXIT_FAILURE);
    }



    // Generate FID table from local_fids.h
/*
//#ifndef __LOCAL_FIDS_H__
//#define __LOCAL_FIDS_H__
#define EID		1

#define FID_MAIN        1
..
*/
    eid_int = -1;
    while ((s_pos = fgets(inp_line, sizeof(inp_line), fid_file)))
    {
        if (eid_int < 0) 
        {
            rc = sscanf(inp_line, "#define EID %i", &eid_int);
            if (rc == 1) 
            {
                fprintf(stderr, "dbgout: %-3d EID\n", eid_int);
                continue;
            }
        }

        rc = sscanf(inp_line, "#define FID_%s %i", &fid_str[0], &fid_int);
        if (rc != 2) 
            continue;

        if ((fid_int >= MAX_FID_NUM) || (strlen(fid_str) >= MAX_FID_LEN)) 
            continue;

        
        fprintf(stderr, "dbgout: %-3d FID_%s\n", fid_int, fid_str);
        strcpy(&fid_tbl[fid_int][0], fid_str);
    }

    /*     
       Parse all local FIDs from files. Input generated by grep.
    */

/*  Input example:
acceler.c:#define LOCAL_FILE_ID FID_ACCELER
acceler.c:#define LOCAL_FILE_ID FID_ACCELER2
actions.c:#define LOCAL_FILE_ID FID_ACTIONS
main.c:#define LOCAL_FILE_ID FID_MAIN
servos.c:#define LOCAL_FILE_ID FID_SERVOS
unit_tests/unit_test_dbg_buff.c:#define LOCAL_FILE_ID FID_UT_DBG_BUFF
unit_tests/unit_test_servo.c:#define LOCAL_FILE_ID FID_UT_SERVO
*/
    while ((s_pos = fgets(inp_line, sizeof(inp_line), stdin)))
    {
        int i;

        rc = sscanf(inp_line, "%[^:]:#define LOCAL_FILE_ID FID_%s", &fid_fname[0], &fid_str[0]);
        if (rc != 2) 
            continue;
        // Find fid_str in fid table

        fprintf(stderr, "dbgout: fid_name %s, fid_file %s\n", &fid_str[0], &fid_fname[0]);
        for (i = 0; i < MAX_FID_NUM; i++)
        {
            if (fid_tbl[i][0] == 0)
                continue;

            if (0 == strcmp(fid_tbl[i], fid_str))
            {   // Fid found 
                printf("F   %-3d %-3d %s\n", eid_int, i, fid_fname);
                fid_tbl[i][0] = 0;
                break;
            }
        }
    }

    return EXIT_SUCCESS;
}

