#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

char inp_line[2048];
char dbg_log_str[2048];

char fid_str[2048];
char fid_fname[256];
char fid_fname_last[256];
int  fid_int;

#define MAX_FID_NUM     50
#define MAX_FID_FNAME   256

char fid_fname_tbl[MAX_FID_NUM][MAX_FID_FNAME];

FILE *fid_file;

int main(int argc, char* argv[])
{
    int rc;
    char *s_pos, *e_pos;
    memset(fid_fname_tbl, 0, sizeof(fid_fname_tbl));

    if (argc < 2)
    {
        printf("Please specify FID file.\n");
        exit(EXIT_FAILURE);
    }

    fid_file = fopen(argv[1], "r");
    if (NULL == fid_file)
    {
        printf("Can't open FIDs file (%s).\n", argv[1]);
        exit(EXIT_FAILURE);
    }

    // Parse FID file and store in local array
/*
F   1   main.c
F   4   servos.c
F   20  unit_tests/unit_test_dbg_buff.c
F   21  unit_tests/unit_test_servo.c
D   5   1231 "message %(struct_sign) message"
*/

    while ((s_pos = fgets(inp_line, sizeof(inp_line), fid_file)))
    {
        if (inp_line[0] != 'F') continue;

        rc = sscanf(inp_line, "F %i %s", &fid_int, &fid_str[0]);
        if (rc != 2) 
            continue;

        if ((fid_int >= MAX_FID_NUM) || (strlen(fid_str) >= MAX_FID_FNAME)) 
            continue;

        strcpy(&fid_fname_tbl[fid_int][0], fid_str);
    }


    /*     
       Parse all local DBG_LOG_D occurence from files. Input generated by grep.
    */

/*
actions.c:125:    DBG_LOG_D("signature %(HW_INFO) just digit %(uint8_t)",
actions.c-126-              VAR2ADDR_SIZE(gt_hw_info),
actions.c-127-              VAR2ADDR_SIZE(uc_len));
actions.c-128-
actions.c-129-    // Write header
actions.c-130-    uc_rc |= cmd_resp_wr(&uc_fixed_header[0], sizeof(uc_fixed_header));
--
main.c:276:    DBG_LOG_D("Just note");
main.c-277-
main.c:278:    DBG_LOG_D("Just note 1st line"
main.c-279-              "Just note 2nd line", 
main.c-280-              NULL
main.c-281-    );
*/
    memset(fid_fname_last, 0, sizeof(fid_fname_last));
    fid_int = 0;

    while ((s_pos = fgets(inp_line, sizeof(inp_line), stdin)))
    {
        int i, line_num;

        rc = sscanf(inp_line, "%[^:]:%i%:", &fid_fname[0], &line_num);
        if (rc != 2) 
            continue;

        // Find fid_fname in fid table
//        fprintf(stderr, "dbgout: fid_name %s, fid_file %s\n", &fid_str[0], &fid_fname[0]);
        if (0 != strcmp(fid_fname_last, fid_fname))
        {
            fid_int = 0;
            for (i = 0; i < MAX_FID_NUM; i++)
            {
                if (fid_fname_tbl[i][0] == 0)
                    continue;

                if (0 == strcmp(fid_fname_tbl[i], fid_fname))
                {   // Fid found 
                    // printf("F   %-3d %s\n", i, fid_fname);
                    strcpy(fid_fname_last, fid_fname_tbl[i]);
                    fid_int = i;
                    break;
                }
            }
        }

        // Skip of file name not found
        if (fid_int == 0)
            continue;

        // Sanity for line num
        if (line_num > 10000)
            continue;

    
        // Get DBG message. Find text between quotes till semi colon
        e_pos = NULL;                   // Position of closing semicolon
        dbg_log_str[0] = 0;             // Buffer for DBG log string

        do
        {
            // Check closing semicolon
            e_pos = strstr(inp_line, ");");

            s_pos = NULL;
            s_pos = strtok(inp_line, "\""); // Check open quote
            if (s_pos != NULL)
            {
                s_pos = strtok(NULL, "\"");     // Check close quote
                if (s_pos != NULL)
                {
                    strncat(dbg_log_str, s_pos, sizeof(dbg_log_str) -3);
                }
            }

            if (e_pos)                      // Exit if semicolon found
                break;

            // semicolon not found. Get next line
            s_pos = fgets(inp_line, sizeof(inp_line), stdin);
            if (s_pos == NULL)
                break;

        } while (1);

        if (feof(stdin) || ferror(stdin))
            break;

        if (e_pos == NULL)  // semicolon not found - ignore
            continue;

        printf("D   1   %-3d %-5d \"%s\"\n", fid_int, line_num, dbg_log_str);

    } // End of stdin line parser loop



	return EXIT_SUCCESS;
}

